### ISSUE TITLE
意料之外的bug

### ISSUE THREAD

**Issue by BenJaff** [Planshit/Tai#101]
[2023-01-09.log](https://github.com/Planshit/Tai/files/10372591/2023-01-09.log)

**Comment by noberumotto** [comment]
[Tai 1.5.0.0 已发布 →](https://github.com/Planshit/Tai/releases/tag/1.5.0.0) 请更新版本，等待后续反馈。

**Comment by noberumotto** [comment]
已在此版本修复 👉 [Tai1.5.0.1](https://github.com/Planshit/Tai/releases/tag/1.5.0.1)
