### ISSUE TITLE
非简中系统中 中文字体的问题

### ISSUE THREAD

**Issue by WXRIW** [Planshit/Tai#105]
WPF 在英文系统中，中文的默认字体比较怪，所以我一般的做法是 FontFamily="Segoe UI, Microsoft YaHei UI"
![image](https://user-images.githubusercontent.com/62491584/211715782-c91bf824-3daf-44e9-9151-0d2edfc5e924.png)

**Comment by noberumotto** [comment]
thanks!

**Comment by greenhat616** [comment]
补充，克隆项目后更新了一下 nuget 依赖，并且将 target 指定为 .Net Framework 4.8；渲染问题就解决了。目前还未测试 .Net 6。
![图片](https://user-images.githubusercontent.com/41122242/213040032-6a5d2627-d370-41ac-a4f8-1a60fad3619b.png)
cc @noberumotto

**Comment by AlexV525** [comment]
> WPF 在英文系统中，中文的默认字体比较怪

该问题仍持续存在
![image](https://github.com/Planshit/Tai/assets/15884415/d3230965-3119-4ef0-80aa-abcba9c192ab)
![image](https://github.com/Planshit/Tai/assets/15884415/fb97c90e-95b5-4372-a1a4-7e2c518376ff)

**Comment by AlexV525** [comment]
1.5.0.5 貌似效果依旧。
![image](https://github.com/Planshit/Tai/assets/15884415/9083f1d9-55bd-4f4d-81d6-2c9d4461b7c2)
![image](https://github.com/Planshit/Tai/assets/15884415/6950c570-43df-4ba9-baa1-719788110828)
