### ISSUE TITLE
运行目录和应用程序不在同一目录时无法正常运行

### ISSUE THREAD

**Issue by mslxl** [Planshit/Tai#112]
#111 

最简单的复现方式
```powershell
Start-Process -WorkingDirectory $env:TMP '.\Tai.exe'
```
<img width="760" alt="image" src="https://user-images.githubusercontent.com/11132880/212549389-ff16fd6f-d4d1-4957-afc9-725e6aab84a1.png">

运行目录和应用程序不在同一目录时，程序会无法正确读取自身图标，数据库和 AppIcon缓存，但是似乎能正常写出日志

</hr>

上述的无法正确读取自身图标可以通过将 `.ManifestModule.Name` 修改为 `.ManifestModule.FullyQualifiedName` 解决，但是其他问题仍需要改动

https://github.com/Planshit/Tai/blob/2531d120c281464d18812d18c656482f2755fb32/UI/Controls/Window/DefaultWindow.cs#L205-L209

**Comment by noberumotto** [comment]
[Tai 1.5.0.0 已发布 →](https://github.com/Planshit/Tai/releases/tag/1.5.0.0) 请更新版本，等待后续反馈。

**Comment by mslxl** [comment]
问题已解决
