### ISSUE TITLE
系统休眠情况下容易闪退？

### ISSUE THREAD

**Issue by pepedd864** [Planshit/Tai#116]

**Comment by noberumotto** [comment]
[Tai 1.5.0.0 已发布 →](https://github.com/Planshit/Tai/releases/tag/1.5.0.0) 请更新版本，等待后续反馈。

**Comment by noberumotto** [comment]
已在此版本修复 👉 [Tai1.5.0.1](https://github.com/Planshit/Tai/releases/tag/1.5.0.1)
