### ISSUE TITLE
[bug] 统计图表的显示存在问题

### ISSUE THREAD

**Issue by welann** [Planshit/Tai#117]
![image](https://user-images.githubusercontent.com/49773825/214363478-5befd726-f848-48a3-9d2e-fc6c606ca630.png)

当选中按天显示的时候会出现图表超出一大截的情况

**Comment by noberumotto** [comment]
[Tai 1.5.0.0 已发布 →](https://github.com/Planshit/Tai/releases/tag/1.5.0.0) 请更新版本，等待后续反馈。
