### ISSUE TITLE
长期运行后崩溃

### ISSUE THREAD

**Issue by SituChengxiang** [Planshit/Tai#121]
电脑忘关了睡眠了9小时，再开后崩溃    
OS：Microsoft Windows 10 专业工作站版；版本号：19045.2546    
软件版本：1.0.0.4;
日志已上传，有我可以帮忙的地方欢迎邮件我
[2023-01-30.log](https://github.com/Planshit/Tai/files/10535516/2023-01-30.log)

**Comment by SituChengxiang** [comment]
问题再现：此次电脑跑了好久没关机（1天8小时42分）
[2023-02-03.log](https://github.com/Planshit/Tai/files/10572507/2023-02-03.log)
日志已上传，望答复，有需要帮忙的地方随时欢迎邮我

**Comment by noberumotto** [comment]
希望能提供解决方案，谢谢

**Comment by noberumotto** [comment]
[Tai 1.5.0.0 已发布 →](https://github.com/Planshit/Tai/releases/tag/1.5.0.0) 请更新版本，等待后续反馈。

**Comment by sino1641** [comment]
@noberumotto 
1.5版本长时间运行/休眠恢复一段时间仍有几率崩溃，
这次的报错如下：
[log](https://pastebin.com/raw/YvFt7F2S)

**Comment by noberumotto** [comment]
已在此版本修复 👉 [Tai1.5.0.1](https://github.com/Planshit/Tai/releases/tag/1.5.0.1)
