### ISSUE TITLE
统计数据不准确呀！

### ISSUE THREAD

**Issue by JohyC** [Planshit/Tai#128]
我摸鱼用浏览器看了一整天的知乎，使用时间只有34分钟。
早上8点到到12点，13点到下午18点了。好几天了，没统计到相应的数据。

系统 win11
tai 1.4.0.0

日志文件：

[2023-02-08.log](https://github.com/Planshit/Tai/files/10704230/2023-02-08.log)
[2023-02-09.log](https://github.com/Planshit/Tai/files/10704232/2023-02-09.log)
[2023-02-10.log](https://github.com/Planshit/Tai/files/10704233/2023-02-10.log)

![image](https://user-images.githubusercontent.com/38210128/218016926-f0f3cd33-52c5-44af-bcf0-91bc7068b810.png)
![image](https://user-images.githubusercontent.com/38210128/218017112-5d6f7911-dcd0-434f-bdd2-1fd0ca4765bc.png)

**Comment by XCJYO** [comment]
和你一样,有时候统计不上,有时候软件莫名其妙关闭了

**Comment by noberumotto** [comment]
[Tai 1.5.0.0 已发布 →](https://github.com/Planshit/Tai/releases/tag/1.5.0.0) 请更新版本，等待后续反馈。

**Comment by starrycrown** [comment]
![image](https://user-images.githubusercontent.com/113831219/227414896-1adfd248-d08f-4153-b3f0-4ae105fbd199.png)
没有打开资源管理器，但是不知道为啥统计这么长的时间上去？难道不是识别停留最顶层的页面停留时间吗？

**Comment by noberumotto** [comment]
已在1.5.0.3版本中进行优化
