### ISSUE TITLE
1.5版本的窗口大小锁定功能bug

### ISSUE THREAD

**Issue by SACMaker** [Planshit/Tai#136]
此版本的窗口大小锁定功能无法正常工作,会锁定一个比较扁长的大小,无法锁定用户设置的窗口大小.具体实例见下图:
![image](https://user-images.githubusercontent.com/43346914/222605990-382e6c94-8c3c-4f20-9cd7-594133da9a68.png)

**Comment by noberumotto** [comment]
已在此版本修复 👉 [Tai1.5.0.1](https://github.com/Planshit/Tai/releases/tag/1.5.0.1)

**Comment by Subfire** [comment]
> 已在此版本修复 👉 [Tai1.5.0.1](https://github.com/Planshit/Tai/releases/tag/1.5.0.1)

1.5.0.6 版本中仍然有这个bug
