### ISSUE TITLE
导致任务栏崩溃重启

### ISSUE THREAD

**Issue by tljk** [Planshit/Tai#14]
Windows 11 家庭版 21H2 22000.376
复现，在tai keepalive窗口所在的虚拟桌面，桌面无窗口，点击多任务或者是手势唤出都会重启
其他虚拟桌面不会崩溃，有窗口最大化之后不会崩溃

日志1
错误应用程序名称: explorer.exe，版本: 10.0.22000.120，时间戳: 0xe846e749
错误模块名称: Windows.UI.Xaml.dll，版本: 10.0.22000.348，时间戳: 0x003360cd
异常代码: 0xc000027b
错误偏移量: 0x0000000000834af0
错误进程 ID: 0x1544
错误应用程序启动时间: 0x01d7f814417d1738
错误应用程序路径: C:\windows\explorer.exe
错误模块路径: C:\Windows\System32\Windows.UI.Xaml.dll
报告 ID: 82a936ed-5d86-4073-b003-3ea526939f8f
错误程序包全名: 
错误程序包相对应用程序 ID: 
2
故障存储段 ，类型 0
事件名称: APPCRASH
响应: 不可用
Cab ID: 0

问题签名:
P1: explorer.exe
P2: 10.0.22000.120
P3: e846e749
P4: combase.dll
P5: 10.0.22000.282
P6: 426c1ced
P7: 80070057
P8: 000000000005c41b
P9: 
P10: 

附加文件:

可在此处获取这些文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_explorer.exe_9e18538ecb5211ffe9aae1efdd49a2305f660_f0d6a280_116933eb-31de-4259-9e70-47f4652ca59e

分析符号: 
重新检查解决方案: 0
报告 ID: 82a936ed-5d86-4073-b003-3ea526939f8f
报告状态: 4100
哈希存储段: nCab GUID: 0
3
外壳程序意外停止，explorer.exe 被重新启动。
4
故障存储段 1267383427371873465，类型 4
事件名称: APPCRASH
响应: 不可用
Cab ID: 0

问题签名:
P1: explorer.exe
P2: 10.0.22000.120
P3: e846e749
P4: combase.dll
P5: 10.0.22000.282
P6: 426c1ced
P7: 80070057
P8: 000000000005c41b
P9: 
P10: 

附加文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1a774f21-3777-42a3-a627-e46f9b3a0bc1.tmp.WERInternalMetadata.xml

可在此处获取这些文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_explorer.exe_9e18538ecb5211ffe9aae1efdd49a2305f660_f0d6a280_116933eb-31de-4259-9e70-47f4652ca59e

分析符号: 
重新检查解决方案: 0
报告 ID: 82a936ed-5d86-4073-b003-3ea526939f8f
报告状态: 268439552
哈希存储段: 3d6fc532bf627bbbb196a68326b7b4b9nCab GUID: 0

**Comment by noberumotto** [comment]
我的系统11专业版，22000.376，没能复现这个bug，你试试退出Tai再重复这个步骤确认是否是Tai导致的崩溃。其他用户看到这条可以测试一下是否能复现。

**Comment by tljk** [comment]
可能是surface设备比较特别，pro8

**Comment by noberumotto** [comment]
下个版本开始tai keepalive窗口将不再显示，也许能解决这个问题，麻烦到时候你更新测试一下，非常谢谢。

**Comment by noberumotto** [comment]
新版本发布了，有时间还请测试一下问题是否还存在

**Comment by tljk** [comment]
solved
