### ISSUE TITLE
win10睡眠模式的时候还会记录在线时长，可能会导致统计不正确

### ISSUE THREAD

**Issue by TOPdoomed** [Planshit/Tai#147]
![image](https://user-images.githubusercontent.com/42329541/226892403-583b2d50-be1e-42aa-a8be-393f1e15c4e0.png)

**Comment by TOPdoomed** [comment]
已发送

**Comment by noberumotto** [comment]
已在此版本修复 👉 [Tai1.5.0.1](https://github.com/Planshit/Tai/releases/tag/1.5.0.1)
