### ISSUE TITLE
我软件安装怎么运行不了啊。。问

### ISSUE THREAD

**Issue by Shuis004** [Planshit/Tai#159]
同上

**Comment by noberumotto** [comment]
解压了吗？

尝试双击 Tai.exe 启动，正常情况根目录会自动创建 Data 和 Log 文件夹，看一下有没有

**Comment by Shuis004** [comment]
有的。但是一直打不开，双击了没反应

从 Windows 版邮件发送

发件人: Berumotto
发送时间: 2023年4月9日 10:54
收件人: Planshit/Tai
抄送: Shuishui; Author
主题: Re: [Planshit/Tai] 我软件安装怎么运行不了啊。。问 (Issue #159)

解压了吗？
尝试双击 Tai.exe 启动，正常情况根目录会自动创建 Data 和 Log 文件夹，看一下有没有

**Comment by noberumotto** [comment]
有Data文件夹应该启动成功了，没看到右下角的状态栏中有出现Tai的图标吗？进入Log文件夹，如果有文件请贴一下

**Comment by Shuis004** [comment]
看到了看到了，不好意思，，我之前都没注意，以为会直接弹出主界面，，打扰了

从 Windows 版邮件发送

发件人: Berumotto
发送时间: 2023年4月9日 14:59
收件人: Planshit/Tai
抄送: Shuishui; Author
主题: Re: [Planshit/Tai] 我软件安装怎么运行不了啊。。问 (Issue #159)

有Data文件夹应该启动成功了，没看到右下角的状态栏中有出现Tai的图标吗？进入Log文件夹，如果有文件请贴一下
