### ISSUE TITLE
希望能加番茄钟，自动停止计时功能

### ISSUE THREAD

**Issue by anonymous-gy** [Planshit/Tai#162]
番茄钟，就是定时摸鱼的闹钟，摸鱼要讲究劳逸结合
还有比如5分钟之内鼠标没有移动过，没有输入，弹一个窗口询问是否停止计时
如果我忘关电脑了，没有休眠只有熄屏，那是不是ide时间就上天了
摸鱼也要讲基本法啊
（虽然可能会继续增加卡顿，但是可以让用户选择）

**Comment by noberumotto** [comment]
Tai已经自带了自动停止计时的功能，无需手动操作。当检测到鼠标长时间没有移动且没有在播放视频或音乐时会自动停止计时
