### ISSUE TITLE
数据丢失，整个四月没有数据了

### ISSUE THREAD

**Issue by DaTouJun** [Planshit/Tai#170]
[2023-04-29.log](https://github.com/Planshit/Tai/files/11358280/2023-04-29.log)

**Comment by noberumotto** [comment]
是否移动或删除了目录文件呢？请查看一下目录下的data文件夹，确认一下data.db大小，一般超过100kb的情况下数据应该还在的，看了一下日志只是图片丢失了，统计数据应该还在数据库内

**Comment by DaTouJun** [comment]
数据库大小为628KB，之前月份的数据都还在，就4月少了一大块
![image](https://user-images.githubusercontent.com/53028087/236656218-c1051cfb-d32e-498c-9f70-d440739cbc36.png)
