### ISSUE TITLE
提个建议，不知道能不能监控网页，能看到我浏览了哪些网站的时长就好了。

### ISSUE THREAD

**Issue by xujinhui2015** [Planshit/Tai#18]

**Comment by noberumotto** [comment]
首先谢谢你的关注和建议，然后非常抱歉，这个功能不计划实现。Tai的初衷是记录软件使用时长，而不是记录软件中行为的时长。如果你确实非常需要这个功能推荐一款可以记录网页时长的同类型软件：[ActivityWatch](https://github.com/ActivityWatch/activitywatch)，你可以尝试一下~

**Comment by xujinhui2015** [comment]
嗯，我就是从那个软件转到这的，不是很喜欢他们的UI，还是你的好看一些。
