### ISSUE TITLE
如何编译运行这个项目

### ISSUE THREAD

**Issue by banduoba** [Planshit/Tai#186]

**Comment by noberumotto** [comment]
你可能需要具备一定的WPF软件开发知识（https://learn.microsoft.com/zh-cn/dotnet/desktop/wpf/?view=netframeworkdesktop-4.8）

1. 安装Visual Studio 2022开发工具
2. [下载](https://github.com/Planshit/Tai/archive/refs/heads/master.zip)或者使用git克隆Tai代码
3. 双击Tai.sln文件会启动VS工具
4. 在VS中设置 `UI` 为启动项目
5. 在VS中点击生成>生成解决方案
6. 打开 `Tai\UI\bin\(Debug/Release)` 文件夹可以看到生成的 Tai.exe 文件，到此完成编译
