### ISSUE TITLE
Xshell 进程名和图标不显示

### ISSUE THREAD

**Issue by frankwuzp** [Planshit/Tai#19]
平台：Windows 10
进程名称：Xshell
进程路径：C:\Program Files (x86)\NetSarang\Xshell 7\Xshell.exe

期望的效果：有短标题 + 进程的图标

![](https://raw.githubusercontent.com/frankwuzp/pic/master/blog/202201051913551.png)

**Comment by noberumotto** [comment]
谢谢反馈，将会在下一次更新时修复此问题

**Comment by coolzoom** [comment]
notepad++也是，估计是类似问题。
**
![image](https://user-images.githubusercontent.com/10232727/148560145-a0634dee-97dc-48cd-9cc7-3f5ddf930c17.png)
**

**Comment by noberumotto** [comment]
已经更新，请升级版本，[1.0.0.2](https://github.com/Planshit/Tai/releases/tag/1.0.0.2)
