### ISSUE TITLE
按在线时长上下排序有时候有点乱 能否在设置里加一个自定义标签固定排序选项呢?

### ISSUE THREAD

**Issue by TOPdoomed** [Planshit/Tai#191]
![image](https://github.com/Planshit/Tai/assets/42329541/52262538-a80f-47c0-83e7-2e5356d388a5)
谢谢大佬

**Comment by noberumotto** [comment]
昨天刚更新了这个排序问题，版本是1.5.0.1吗

**Comment by TOPdoomed** [comment]
噢好的 这就去更新
