### ISSUE TITLE
开机启动每次都会显示主界面

### ISSUE THREAD

**Issue by NoclubOIRzXx** [Planshit/Tai#211]
版本： [1.5.0.1](https://github.com/Planshit/Tai/releases/tag/1.5.0.1)
开机启动总会在桌面显示窗口，还要手动关闭。

**Comment by Wenbobobo** [comment]
遇到同样情况，~~_好像升级前不会的_~~

**Comment by wangzhen0518** [comment]
+1

**Comment by noberumotto** [comment]
已在1.5.0.3版本中处理此问题
