### ISSUE TITLE
开机自启每次都显示主界面

### ISSUE THREAD

**Issue by BadBoy1477** [Planshit/Tai#236]
不知道是不是新版本“调整了首次启动的行为”的问题，现在每次开机都会弹出主界面窗口，只能手动关闭，使用内置更新器更新前不会有这个问题。

**Comment by dunxuan** [comment]
附议

**Comment by 0w0-Yui** [comment]
附议

**Comment by baddate** [comment]
旧版本(1.4.0.0)没有问题，升级到新版本(1.5.0.1)就有这个问题了。@noberumotto

**Comment by BadBoy1477** [comment]
> 旧版本(1.4.0.0)没有问题，升级到新版本(1.5.0.1)就有这个问题了。@noberumotto

1.5.0.0也没有问题

**Comment by baddate** [comment]
> > 旧版本(1.4.0.0)没有问题，升级到新版本(1.5.0.1)就有这个问题了。@noberumotto
> 
> 
> 
> 1.5.0.0也没有问题

Emmm，这个小版本改的呀……
不会是新功能吧😆

**Comment by yeungchie** [comment]
附议

**Comment by noberumotto** [comment]
非常抱歉这个功能给大家带来困扰，后续新版本会移除
