### ISSUE TITLE
联网功能请求

### ISSUE THREAD

**Issue by KargathEx** [Planshit/Tai#249]
作者是否有打算添加联网功能，做成类似`番茄TODO自习室`的东西，这样分隔异地的人可以看到其他人在做什么，以及一天下来都做了什么，更方便互相监督。
因为我搜到`番茄TODO自习室`似乎只有手机端，且pc端有类似功能的软件很少，尤其是这种能精确记录又比`屏幕分享`隐私性更好的。

**Comment by lxl66566** [comment]
联网的话就涉及到服务器了，感觉大概率不会（
这个功能，应该可以通过 bot 实现

**Comment by noberumotto** [comment]
暂时不考虑此功能哦
