### ISSUE TITLE
也想要 mac 端

### ISSUE THREAD

**Issue by seyeeL** [Planshit/Tai#253]

**Comment by noberumotto** [comment]
mac应该有跟iPhone一样的屏幕使用时长吧？

**Comment by seyeeL** [comment]
> mac应该有跟iPhone一样的屏幕使用时长吧？

数据比较粗糙，统计结果展示也是

**Comment by noberumotto** [comment]
因为目前没有Mac机器，所以短期内不会开发Mac端哦，谢谢您的支持

**Comment by liuyuyan2717** [comment]
> 因为目前没有Mac机器，所以短期内不会开发Mac端哦，谢谢您的支持

众筹捐一台机器
