### ISSUE TITLE
网站数据没法记录

### ISSUE THREAD

**Issue by yb123speed** [Planshit/Tai#262]
应用使用数据记录正常，但是网站没有任何记录数据
![image](https://github.com/Planshit/Tai/assets/9018559/99f8702e-419e-4667-9ebb-0d3651dcb02f)

Tai 版本号 1.5.0.1
版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎3/‎27
操作系统版本	22621.2134
体验	Windows Feature Experience Pack 1000.22659.1000.0

**Comment by noberumotto** [comment]
需要手动在设置开启。但是当前版本网站记录功能有问题，会不定时引发程序闪退，请等下一个版本再使用

**Comment by CheneyWong** [comment]
不知道是什么机制？用的 360 极速浏览器，好像没法支持。未来能不能自定义？

**Comment by noberumotto** [comment]
> 不知道是什么机制？用的 360 极速浏览器，好像没法支持。未来能不能自定义？

目前暂不支持360浏览器。未来的版本需要安装浏览器插件来进行统计，只要是常见的非冷门浏览器都会支持的

**Comment by noberumotto** [comment]
请升级到1.5.0.3版本，网页数据统计需要依赖Tai浏览器插件
[Tai Chrome浏览器拓展.zip](https://github.com/Planshit/Tai/files/13177982/Tai.Chrome.zip)
