### ISSUE TITLE
系统更新之后启动闪退

### ISSUE THREAD

**Issue by haze-0819** [Planshit/Tai#273]
更新到Windows10 KB5031356 (操作系统内部版本 19044.3570 和 19045.3570)后，无法正常启动，更新前可以正常使用。

以下是部分日志：
[Info] 2023-10-12 10:00:01
datetime observer start,interval(s):3597.9999057
Line:40,File:Tai\Servicers\Instances\DateTimeObserver.cs,name:SetTimer
------------------------

[Info] 2023-10-12 10:00:40
Active[True]:msedge,Last:msedge,Time:2023/10/12 9:59:58
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:00:47
Active[True]:msedge,Last:msedge,Time:2023/10/12 9:59:58
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:01:37
Active[True]:msedge,Last:msedge,Time:2023/10/12 9:59:58
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:01:39
Active[True]:msedge,Last:msedge,Time:2023/10/12 9:59:58
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:04:30
Active[True]:msedge,Last:msedge,Time:2023/10/12 9:59:58
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:04:31
Active[True]:notepad,Last:msedge,Time:2023/10/12 9:59:58
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:04:31
Save app time done.Process:msedge,Duration:272,StartDateTime:2023/10/12 10:00:00,AppID:2
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:04:47
Active[True]:msedge,Last:notepad,Time:2023/10/12 10:04:31
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:04:47
Save app time done.Process:notepad,Duration:16,StartDateTime:2023/10/12 10:04:31,AppID:20
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:04:48
Active[True]:msedge,Last:msedge,Time:2023/10/12 10:04:47
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:05
Active[False]:,Last:msedge,Time:2023/10/12 10:04:47
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:05
Save app time done.Process:msedge,Duration:197,StartDateTime:2023/10/12 10:04:47,AppID:2
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:08:05
Active[False]:,Last:,Time:2023/10/12 10:08:05
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:06
Active[False]:,Last:,Time:2023/10/12 10:08:05
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:07
Active[True]:msedge,Last:,Time:2023/10/12 10:08:05
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:11
Active[True]:explorer,Last:msedge,Time:2023/10/12 10:08:07
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:11
Save app time done.Process:msedge,Duration:3,StartDateTime:2023/10/12 10:08:07,AppID:2
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:08:18
Active[False]:,Last:explorer,Time:2023/10/12 10:08:11
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:18
Save app time done.Process:explorer,Duration:7,StartDateTime:2023/10/12 10:08:11,AppID:1
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:08:18
Active[False]:,Last:,Time:2023/10/12 10:08:18
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:19
Active[False]:,Last:,Time:2023/10/12 10:08:18
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:27
Active[True]:explorer,Last:,Time:2023/10/12 10:08:18
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:33
Active[False]:OpenWith,Last:explorer,Time:2023/10/12 10:08:27
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:33
Save app time done.Process:explorer,Duration:5,StartDateTime:2023/10/12 10:08:27,AppID:1
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:08:36
Active[False]:,Last:,Time:2023/10/12 10:08:33
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:36
Active[True]:notepad,Last:,Time:2023/10/12 10:08:33
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:50
Active[True]:explorer,Last:notepad,Time:2023/10/12 10:08:36
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:50
Save app time done.Process:notepad,Duration:13,StartDateTime:2023/10/12 10:08:36,AppID:20
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:08:58
Active[False]:OpenWith,Last:explorer,Time:2023/10/12 10:08:50
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:08:58
Save app time done.Process:explorer,Duration:8,StartDateTime:2023/10/12 10:08:50,AppID:1
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:09:01
Active[False]:,Last:,Time:2023/10/12 10:08:58
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:09:01
Active[True]:notepad,Last:,Time:2023/10/12 10:08:58
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:09:07
Active[True]:explorer,Last:notepad,Time:2023/10/12 10:09:01
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:09:07
Save app time done.Process:notepad,Duration:5,StartDateTime:2023/10/12 10:09:01,AppID:20
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:09:10
Active[True]:msedge,Last:explorer,Time:2023/10/12 10:09:07
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:09:10
Save app time done.Process:explorer,Duration:3,StartDateTime:2023/10/12 10:09:07,AppID:1
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

[Info] 2023-10-12 10:09:29
Active[True]:SystemSettings,Last:msedge,Time:2023/10/12 10:09:10
Line:351,File:Tai\Servicers\Instances\Main.cs,name:AppObserver_OnAppActive
------------------------

[Info] 2023-10-12 10:09:29
Save app time done.Process:msedge,Duration:19,StartDateTime:2023/10/12 10:09:10,AppID:2
Line:113,File:Tai\Servicers\Instances\Data.cs,name:SaveAppDuration
------------------------

**Comment by noberumotto** [comment]
提供一下windows日志，打开事件查看器（可以通过任务栏左下角搜索功能找到），选择windows日志，选择应用程序，找到Tai任务类别为异常崩溃类型的记录，双击复制异常信息贴一下

**Comment by haze-0819** [comment]
感谢您的回复，但是好像今天又正常了，奇怪
