### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by younger-1** [Planshit/Tai#28]
请增加license保护自己的软件著作权

**Comment by noberumotto** [comment]
我想这软件应该不会被很多人发现和使用，加上没有什么技术含量所以就没加license。而且我对license不是很了解，是否有必要加上呢？我是允许拿去修改二次分发甚至商用的。

**Comment by younger-1** [comment]
其实开源软件加了合适的license后，第三方使用者也能更加放心地使用其源代码。
根据你的需要，可以使用[MIT](https://tldrlegal.com/license/mit-license) 或 [Unlicense](https://unlicense.org/)

**Comment by noberumotto** [comment]
好的了解，非常谢谢。
