### ISSUE TITLE
最新版程序崩溃，疑似和睡眠监测有关？

### ISSUE THREAD

**Issue by DaTouJun** [Planshit/Tai#281]
[2023-10-27.log](https://github.com/Planshit/Tai/files/13180253/2023-10-27.log)

**Comment by DaTouJun** [comment]
[Error] 2023-10-27 00:36:48
[程序崩溃异常] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Core.Servicers.Instances.WebServer.SendMsg(String msg_)
   在 Core.Servicers.Instances.Main.Sleepdiscover_SleepStatusChanged(SleepStatus sleepStatus)
   在 Core.Servicers.Instances.Sleepdiscover.Sleep()
   在 Core.Servicers.Instances.Sleepdiscover.<Timer_Tick>d__24.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Line:60,File:Tai\App.xaml.cs,name:App_DispatcherUnhandledException
------------------------

**Comment by DaTouJun** [comment]
[Error] 2023-10-27 00:36:48
[程序崩溃异常] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Core.Servicers.Instances.WebServer.SendMsg(String msg_)
   在 Core.Servicers.Instances.Main.Sleepdiscover_SleepStatusChanged(SleepStatus sleepStatus)
   在 Core.Servicers.Instances.Sleepdiscover.Sleep()
   在 Core.Servicers.Instances.Sleepdiscover.<Timer_Tick>d__24.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Line:60,File:Tai\App.xaml.cs,name:App_DispatcherUnhandledException
------------------------

**Comment by noberumotto** [comment]
已发布修复更新版本1.5.0.4，请更新。非常谢谢您及时反馈
