### ISSUE TITLE
睡眠了仍然继续统计

### ISSUE THREAD

**Issue by DaTouJun** [Planshit/Tai#287]
![image](https://github.com/Planshit/Tai/assets/53028087/572e2230-72c7-4031-bef5-5180bae6ef0a)

**Comment by noberumotto** [comment]
有没有在设置，行为中关闭了睡眠监测呢？如果没有提供一下当天的log

**Comment by DaTouJun** [comment]
好像确实是关了，因为之前那个版本会崩掉，关了之后自动升级了也是关的
