### ISSUE TITLE
有计划出Arm架构的版本吗？

### ISSUE THREAD

**Issue by XiaoLFeng** [Planshit/Tai#290]
有计划出Windows下Arm架构的版本吗？

**Comment by WXRIW** [comment]
引用的 System.Data.SQLite 没有提供 Arm64，所以暂时无法推出 Arm64 版本。
目前可直接使用 x64 (项目是支持 x64 的，并且取消勾选了 Prefer 32-bit，但不知道为什么 Releases 里的是以 x86 运行的；所以你可以手动编译一份使用)。
.NET 项目的 x64 性能与 Arm64 的差距不是很大，x86 效率会较低。

**Comment by XiaoLFeng** [comment]
OKOK，谢谢
