### ISSUE TITLE
启动崩溃 无法加载 DLL“SQLite.Interop.dll”:

### ISSUE THREAD

**Issue by xiaoding2333** [Planshit/Tai#297]
Core Version:1.1.0.5
OS Name:Microsoft Windows 11 企业版
Computer Type:Laptop
Screen:2560*1600

++++++++++++++++++++++++++++++++++++++++++++++++++

[Error] 2023-11-22 14:50:39
[程序崩溃异常] System.DllNotFoundException: 无法加载 DLL“SQLite.Interop.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   在 System.Data.SQLite.SQLite3.StaticIsInitialized()
   在 System.Data.SQLite.SQLiteLog.PrivateInitialize(String className)
   在 System.Data.SQLite.SQLiteLog.Initialize(String className)
   在 System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   在 System.Data.SQLite.SQLiteConnection..ctor()
   在 Core.Librarys.SQLite.TaiDbContext..ctor()
   在 Core.Servicers.Instances.Main.<Run>b__28_0()
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Core.Servicers.Instances.Main.<Run>d__28.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Line:60,File:Tai\App.xaml.cs,name:App_DispatcherUnhandledException
------------------------

**Comment by noberumotto** [comment]
在 Tai 根目录下查看有没有名字为 x86/x64 的文件夹，如果有，进入系统类型对应的文件夹里面将 SQLite.Interop.dll 文件复制到 Tai 根目录；如果没有请重新下载Tai压缩包覆盖到根目录。

**Comment by xiaoding2333** [comment]
可以了 多谢 很好用的软件
