### ISSUE TITLE
启动程序崩溃

### ISSUE THREAD

**Issue by SliverKeigo** [Planshit/Tai#302]
下载后启动程序直接崩溃
![image](https://github.com/Planshit/Tai/assets/112426853/d40f74c1-2501-4941-888a-1885b0e59c6c)
崩溃日志为：
Core Version:1.1.0.5
OS Name:Microsoft Windows 11 专业版
Computer Type:Desktop
Screen:1920*1200

++++++++++++++++++++++++++++++++++++++++++++++++++

[Error] 2023-12-10 16:14:50
[程序崩溃异常] System.TypeInitializationException: “System.Data.Entity.Internal.AppConfig”的类型初始值设定项引发异常。 ---> System.Configuration.ConfigurationErrorsException: 配置系统未能初始化 ---> System.Configuration.ConfigurationErrorsException: 无法识别的配置节 startup。 (D:\Tai\Tai1.5.0.5\Tai.exe.Config line 3)
   在 System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   在 System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   在 System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   在 System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Configuration.ConfigurationManager.PrepareConfigSystem()
   在 System.Configuration.ConfigurationManager.get_ConnectionStrings()
   在 System.Data.Entity.Internal.AppConfig..ctor()
   在 System.Data.Entity.Internal.AppConfig..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Data.Entity.Internal.AppConfig.get_DefaultInstance()
   在 System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.EnsureLoadedForAssembly(Assembly assemblyHint, Type contextTypeHint)
   在 System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.EnsureLoadedForContext(Type contextType)
   在 System.Data.Entity.DbContext.InitializeLazyInternalContext(IInternalConnection internalConnection, DbCompiledModel model)
   在 System.Data.Entity.DbContext..ctor(DbConnection existingConnection, Boolean contextOwnsConnection)
   在 Core.Librarys.SQLite.TaiDbContext..ctor()
   在 Core.Servicers.Instances.Main.<Run>b__28_0()
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Core.Servicers.Instances.Main.<Run>d__28.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Line:60,File:Tai\App.xaml.cs,name:App_DispatcherUnhandledException
------------------------

查看config之后

![image](https://github.com/Planshit/Tai/assets/112426853/dd8d9980-d9ed-45b1-b606-3977ce4d5a2a)

  <startup>节点无效
  
环境正常

![image](https://github.com/Planshit/Tai/assets/112426853/0560d96a-7283-49e5-b8fb-ea94b470e87c)

**Comment by noberumotto** [comment]
把配置文件你圈起来的部分删掉再启动试试

**Comment by SliverKeigo** [comment]
> 把配置文件你圈起来的部分删掉再启动试试

之前试过了,还是抛出异常无法识别的配置节 runtime

**Comment by noberumotto** [comment]
下载最新的1.5.0.6版本试试
