### ISSUE TITLE
应用按目录匹配分类似乎没有正确工作

### ISSUE THREAD

**Issue by AlexiousLu** [Planshit/Tai#306]
版本：v1.5.0.5
平台：win10 22H2

我创建了一个分类"游戏"包含两个路径：

![image](https://github.com/Planshit/Tai/assets/42344775/98146e2e-da32-4246-9628-e48631cb5339)

然而在统计中其中一个路径下的应用并未被统计进去

![image](https://github.com/Planshit/Tai/assets/42344775/80e6bc42-827c-4cd0-b1ab-2fd9f7df25c4)

不像是直接按照应用被分类的应用，比如：

![image](https://github.com/Planshit/Tai/assets/42344775/42d23a51-2516-489c-aeb3-319ba9ccc9de)

请问是我设置的问题，还是这个版本的bug呢？谢谢大佬

**Comment by noberumotto** [comment]
在保存分类后 `bg3.exe` 是否运行过呢？需要该应用在设置分类后运行一次才能自动分类的哦

**Comment by AlexiousLu** [comment]
> 在保存分类后 `bg3.exe` 是否运行过呢？需要该应用在设置分类后运行一次才能自动分类的哦

好像是因为我在创建分类前运行过bg3.exe，之后创建了分类，bg3.exe还是无标签状态。我尝试运行了一个安装Tai之后未运行过的、在两个分类路径下的应用，就可以看到"游戏"标签了。

**Comment by noberumotto** [comment]
是的 需要先设置路径匹配后运行一次应用才能自动分类
