### ISSUE TITLE
能否整合应用和网站信息到一起？

### ISSUE THREAD

**Issue by Xiangyu-Fu** [Planshit/Tai#312]
首先感谢开发这款应用！ 真的非常有帮助！ 但是我发现大部分时间都会使用在chrome中，主要分为娱乐和学习。但现在的版本中，详细信息很难直观的表现出学习了多久和娱乐了多久，所以能否把网页和应用信息做一个整合呢? 例如把bilibli的时间算入娱乐，把GitHub时间算作学习，这样更直观一些。谢谢！

**Comment by noberumotto** [comment]
可以对站点分类呀，然后统计页可以切换网站数据查看

**Comment by Xiangyu-Fu** [comment]
就是能不能不切换，把两个信息整合到一起呢？

**Comment by noberumotto** [comment]
> 就是能不能不切换，把两个信息整合到一起呢？

目前暂时没有想到比较好的方案和设计呢

**Comment by Xiangyu-Fu** [comment]
OK 感谢回复 希望未来版本能加入！
