### ISSUE TITLE
变更窗口焦点的时候是不是同步变更了Tai窗口展示的内容，感觉有点卡顿，不知道能不能改成异步的

### ISSUE THREAD

**Issue by jliu666** [Planshit/Tai#32]
还有就是Tai窗口变更内容的时候能不能增加动画，现在感觉顺序变更的时候特别卡顿，

**Comment by noberumotto** [comment]
Tai概览页是会实时刷新数据。关于卡顿我正在寻找解决方案中，谢谢反馈。

**Comment by noberumotto** [comment]
> 电脑锁屏好像也在统计😂

是统计的时间超过十个小时了吗？那就奇怪了，五分钟没有操作应该会进入睡眠状态的，锁屏的时候是否在播放音乐或视频呢？

**Comment by jliu666** [comment]
> > 电脑锁屏好像也在统计😂
> 
> 是统计的时间超过十个小时了吗？那就奇怪了，五分钟没有操作应该会进入睡眠状态的，锁屏的时候是否在播放音乐或视频呢？

我设置了不休眠，只锁屏，我是程序员🙄

**Comment by noberumotto** [comment]
> 

是笔记本电脑吗？

**Comment by jliu666** [comment]
> > 
> 
> 是笔记本电脑吗？

是台式机的，

**Comment by noberumotto** [comment]
好的谢谢反馈，在下一次碰到这个情况的时候麻烦告诉我一下复现的流程。

**Comment by jliu666** [comment]
> 好的谢谢反馈，在下一次碰到这个情况的时候麻烦告诉我一下复现的流程。

使计算机进入睡眠 从不
就可以了吧，没有其他的复现流程，这是必现的吧，第二天过来有软件已经统计几个小时了

**Comment by noberumotto** [comment]
已经更新，试试是否解决问题，[1.0.0.2](https://github.com/Planshit/Tai/releases/tag/1.0.0.2)
