### ISSUE TITLE
大佬，如果想实现某个程序激活时向一个云函数发起请求要改那部分代码？

### ISSUE THREAD

**Issue by rebron1900** [Planshit/Tai#336]
最近看到 https://innei.in/ 这个大佬的博客有一个实时状态的功能，可以实时显示他在用什么工具。
我想结合Tai试试实现一下这个功能。

**Comment by noberumotto** [comment]
那这个项目应该很适合你，https://github.com/gettai/sentry

**Comment by noberumotto** [comment]
要在Tai中实现此功能的话如下所示

`IAppObserver` 服务提供了焦点监听功能，在任意地方都能通过服务中的 `OnAppActiveChanged` 事件拿到当前激活的程序。

比如在 `https://github.com/Planshit/Tai/blob/master/Core/Servicers/Instances/Main.cs`   `public void Start()` 方法中添加以下代码

Main.cs 
```c#
public void Start(){
...
  appObserver.OnAppActiveChanged += OnAppActived;
}
```


```c#
...
private void OnAppActived(object sender, AppActiveChangedEventArgs e){            
  //  进程名称
  string processName = e.App.Process;
...
//  编写请求云端代码...
}
```

**Comment by rebron1900** [comment]
感谢，我研究一下，有疑问的话再来请教，忘不吝赐教

**Comment by noberumotto** [comment]
我看到会尽力协助你的

**Comment by rebron1900** [comment]
感谢，已经用其他方式实现了
