### ISSUE TITLE
请问全屏运行的游戏好像只能读取到几秒钟，比如CS2和刺客信条兄弟会

### ISSUE THREAD

**Issue by xiaohuaihai** [Planshit/Tai#338]
记录是记录了，但是只有几秒钟，不太清楚是什么原因
（刚又看了一下好像正常的）

**Comment by xiaohuaihai** [comment]
挂在后台的什么音乐软件好像也只读到十几秒欸，感觉是什么设置没开？还是什么问题

**Comment by xiaohuaihai** [comment]
全屏游戏无法统计到，后台音乐播放因为不在焦点也无法检测，但是如果加上后台的话是会统计到很多的系统进程嘛

**Comment by noberumotto** [comment]
这个版本开发之初就不考虑统计没有焦点的进程。下一个版本会加入一个 `闲置时长` （暂定名称）数据，你可以把它看作后台时长。全屏游戏无法统计这个问题也会在下一个版本进行修复
