### ISSUE TITLE
查看详细就报错 重装也一样

### ISSUE THREAD

**Issue by wangrui1573** [Planshit/Tai#36]
[Error] [2022-02-11 19:47:27] 
[程序崩溃异常] 该字符串未被识别为有效的 DateTime。
[Caller Info] Line:58,File:Tai\App.xaml.cs,name:App_DispatcherUnhandledException

**Comment by noberumotto** [comment]
抱歉，处理得有点晚了，如果方便请下载此版本测试一下是否能解决此问题。
[tai20220306 test.zip](https://github.com/Planshit/Tai/files/8191352/tai20220306.test.zip)

**Comment by XiaoDuComrade** [comment]
您好！我遇到了同样的问题！在查看详细时报错
[Error] [2022-06-02 08:19:01] 
[程序崩溃异常] 未找到适用于完成此操作的图像处理组件。
[Caller Info] Line:58,File:Tai\App.xaml.cs,name:App_DispatcherUnhandledException
------------
[2022-06-02.log](https://github.com/Planshit/Tai/files/8819535/2022-06-02.log)
------------

**Comment by noberumotto** [comment]
@XiaoDuComrade 查看所有软件的详细都报错还是只有某一个才会出现呢？

**Comment by XiaoDuComrade** [comment]
> ## 您好！我遇到了同样的问题！在查看详细时报错
> [Error] [2022-06-02 08:19:01]
> [程序崩溃异常] 未找到适用于完成此操作的图像处理组件。
> [Caller Info] Line:58,File:Tai\App.xaml.cs,name:App_DispatcherUnhandledException
> ## [2022-06-02.log](https://github.com/Planshit/Tai/files/8819535/2022-06-02.log)

点击主界面左侧的“详细”图标，直接崩溃。

**Comment by XiaoDuComrade** [comment]
点击主界面左侧的“详细”图标，直接崩溃，稳定崩溃，已经是最新版本软件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 中午1:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Planshit/Tai] 查看详细就报错 重装也一样 (Issue #36)





 
@XiaoDuComrade 查看所有软件的详细都报错还是只有某一个才会出现呢？

**Comment by XiaoDuComrade** [comment]
开发者您好！经过我简单测试，直接运行软件并没有问题，将原先的Date数据迁移仍可正常使用，但当我把原先的AppIcons迁移过去之后稳定出现此bug，图标文件夹内共263个项目，占800+kb,我已将此文件夹添加到附件，希望能帮助您改进软件！
不常使用GitHub，如有冒犯还请多多包涵。
祝您软件越做越好！期待您的回复
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Planshit/Tai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月2日(星期四) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Planshit/Tai] 查看详细就报错 重装也一样 (Issue #36)





 
@XiaoDuComrade 查看所有软件的详细都报错还是只有某一个才会出现呢？

**Comment by noberumotto** [comment]
非常谢谢，但是我似乎没看到图标附件，这些图标对于处理问题非常有帮助

**Comment by XiaoDuComrade** [comment]
我尝试重新将文件添加到邮件附件中了，同时会上传到GitHub issues中，如果还没收到麻烦联系我




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Planshit/Tai"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月2日(星期四) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Planshit/Tai] 查看详细就报错 重装也一样 (Issue #36)





 
非常谢谢，但是我似乎没看到图标附件，这些图标对于处理问题非常有帮助

**Comment by XiaoDuComrade** [comment]
[AppIcons.zip](https://github.com/Planshit/Tai/files/8823002/AppIcons.zip)
[Data.zip](https://github.com/Planshit/Tai/files/8823004/Data.zip)

**Comment by noberumotto** [comment]
> 我尝试重新将文件添加到邮件附件中了，同时会上传到GitHub issues中，如果还没收到麻烦联系我
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Planshit/Tai" ***@***.***&gt;; 发送时间:&nbsp;2022年6月2日(星期四) 晚上6:31 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Planshit/Tai] 查看详细就报错 重装也一样 (Issue #36) 非常谢谢，但是我似乎没看到图标附件，这些图标对于处理问题非常有帮助 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

看到了，感谢。

**Comment by noberumotto** [comment]
1.0.0.3版本已修复
