### ISSUE TITLE
在年视图中出现了一个不正常高数据的软件

### ISSUE THREAD

**Issue by Ovler-Young** [Planshit/Tai#38]
https://user-images.githubusercontent.com/44089074/158184563-df5e8c10-c5d5-4aba-8f6a-7e6ef7f1041a.mp4

还有一个错位的问题

https://user-images.githubusercontent.com/44089074/158184844-d5fca6ba-de10-4b3a-a428-5fa540c8d9a7.mp4

**Comment by noberumotto** [comment]
手动清空一下数据，升级到此版本试试。[1.0.0.2](https://github.com/Planshit/Tai/releases/tag/1.0.0.2)

**Comment by Ovler-Young** [comment]
> 手动清空一下数据，升级到此版本试试。[1.0.0.2](https://github.com/Planshit/Tai/releases/tag/1.0.0.2)

没有效果。经排查发现log文件夹下有一个文件名为 `2022-12-31.json` 且修改时间为2022年2月12日。
查看数据库发现，该记录上下外均为2月12日记录。
![数据库图片](https://user-images.githubusercontent.com/44089074/167913144-86928b12-c0b1-4266-9e3f-2334835e26ee.png)
且，再未有过复现。
故怀疑是系统时间或程序获取的时间可能出现了一次随机的问题。

另：可以通过数据库中id递增时，Date字段应不变或变大，若id增大而Date字段变小，可以认为该数据存在问题，可作为日后自检的一种方式。

**Comment by noberumotto** [comment]
谢谢反馈。麻烦将2022-12-31.json的log文件贴一下

**Comment by Ovler-Young** [comment]
抱歉已经删了……
