### ISSUE TITLE
Errors in Log file

### ISSUE THREAD

**Issue by wao1201** [Planshit/Tai#4]
App Version: v1.0
OS Version: Win10 21H1
==================================
[Error] [2021-12-14 14:11:57] 
路径的形式不合法。 | Process Name:Taskmgr | Process File: | Process Description:
[Caller Info] Line:82,File:C:\Users\Banpocat\source\repos\Tai\Core\Servicers\Instances\Observer.cs,name:WinEventProc
------------------------
==================================

**Comment by noberumotto** [comment]
这个无需理会不影响任何使用，Taskmgr进程也是在忽略名单中的
