### ISSUE TITLE
tai对steam里的游戏统计时长有问题

### ISSUE THREAD

**Issue by denyeye** [Planshit/Tai#40]
![VF87$Z KDIK} P5GDL}P56V](https://user-images.githubusercontent.com/42514804/163353359-65867d16-6aab-44be-a653-fce10bccf249.png)

**Comment by denyeye** [comment]
每个游戏都只能记录几分钟

**Comment by denyeye** [comment]
我发现是帧数监测软件(steam自带或者afterburner)会影响屏幕焦点的判定

**Comment by noberumotto** [comment]
steam自带的帧数显示我打开后测试正常欸
