### ISSUE TITLE
[修复] 用鼠标侧键返回上层之后UI工作不正常

### ISSUE THREAD

**Issue by sunphobia** [Planshit/Tai#42]
![image](https://user-images.githubusercontent.com/83940761/164752082-689aee4e-5b7a-4050-9615-0771ed4bf042.png)
详细里点进去一个程序
![image](https://user-images.githubusercontent.com/83940761/164752126-23d99885-5f66-479c-87ab-ca9719a175e5.png)
然后鼠标侧键返回上层
![image](https://user-images.githubusercontent.com/83940761/164752222-d4a79a21-5f0b-4de0-b1c6-dae71aa324a4.png)
左上角的返回箭头还在 而且再点程序详情也点不开了
要手动点一下左上角的返回键之后才能恢复正常

**Comment by noberumotto** [comment]
`1.0.0.4` 版本已修复
