### ISSUE TITLE
Feature Request: 提供顺序时间视图

### ISSUE THREAD

**Issue by H4M5TER** [Planshit/Tai#46]
我希望能知道，我在某个时间段内，焦点都在什么上或在什么之间移动（乃至键盘和鼠标的活动和活动频率，当然，只是说说）
这应该是比较符合这个软件统计行为的思路的，所以我希望有一个类似这样的视图：
![91D3D65D4D92399B03592990D4DB1D6C](https://user-images.githubusercontent.com/21092951/171078206-8380e843-27e9-4ece-ba7a-9d6e30fb0eae.jpg)

**Comment by noberumotto** [comment]
👌已经在开发计划中，开的坑有点多忙不过来了

**Comment by noberumotto** [comment]
在1.0.0.3版本已加入
