### ISSUE TITLE
能不能导出每个软件每天的使用时长，使用次数等数据到excel

### ISSUE THREAD

**Issue by ningxia2022** [Planshit/Tai#58]
能不能导出每个软件每天的使用时长，点击次数等数据到excel，这样更好统计保存记录。
也可以参照浏览器插件Web Activity Time Tracker制作一些time chart等功能
谢谢啦，尤其想要导出功能

**Comment by noberumotto** [comment]
导出数据功能在开发中了，但是很抱歉进度可能比较慢，因为最近大部分时间都是在工作上

**Comment by noberumotto** [comment]
抱歉有些晚了，数据导出功能已经加入了，如果还在用Tai的话记得更新~
