### ISSUE TITLE
tai统计时长异常

### ISSUE THREAD

**Issue by dreamstring** [Planshit/Tai#59]
![image](https://user-images.githubusercontent.com/42427281/185733860-64c4525f-d0d5-49fe-89c8-103ca3177393.png)
打开的软件基本都没有被正常统计时长，adobe系软件尤其严重，系统是win 11。

**Comment by noberumotto** [comment]
截图中的软件时长都不对吗？

**Comment by dreamstring** [comment]
是的，当天我用了AE AI都至少4小时，因为之前就觉得不对劲，所以昨天特意关注了下

**Comment by dreamstring** [comment]
![image](https://user-images.githubusercontent.com/42427281/185742415-54325f02-a8fc-4566-b550-b94a665a4d06.png)
这是今天的数据，中午12点就开始用电脑，所以无论是QQ还是AE应该至少3小时以上

**Comment by lxymahatma** [comment]
win11系统有些软件还会统计错误比如用vs2022的时候统计成2019
![image](https://user-images.githubusercontent.com/66151783/185751735-144e4460-24f3-41d7-94d9-184bea4a425e.png)
虽然显示了路径但是电脑上压根就没有装2019版本的vs
![image](https://user-images.githubusercontent.com/66151783/185751740-320d6a7f-3a79-41ca-be02-b5b76904bc25.png)

**Comment by noberumotto** [comment]
已经发布更新，如果能正常工作请关闭此issue。[https://github.com/Planshit/Tai/releases/tag/1.0.0.5](https://github.com/Planshit/Tai/releases/tag/1.0.0.5)

**Comment by lxymahatma** [comment]
![image](https://user-images.githubusercontent.com/66151783/190843939-e580cbd5-1d95-4e5a-bd17-45b89b27460b.png)
更新之后仍然是显示2019版本的vs在使用，是需要清除统计才有用还是仍然是bug

**Comment by noberumotto** [comment]
> 更新之后仍然是显示2019版本的vs在使用，是需要清除统计才有用还是仍然是bug

清除统计可能无法完全删除应用信息，建议将Data\data.db删除后重启软件试试

**Comment by lxymahatma** [comment]
> > 更新之后仍然是显示2019版本的vs在使用，是需要清除统计才有用还是仍然是bug
> 
> 清除统计可能无法完全删除应用信息，建议将Data\data.db删除后重启软件试试

已正常，就是之前记录的时间没有了，不过无伤大雅
