### ISSUE TITLE
程序意外崩溃

### ISSUE THREAD

**Issue by onelizi** [Planshit/Tai#64]
我的设备信息：
版本	Windows 10 专业版
版本号	21H1
操作系统内部版本	19043.2006
体验	Windows Feature Experience Pack 120.2212.4180.0

以下是崩溃日志：
[2022-10-04.log](https://github.com/Planshit/Tai/files/9704290/2022-10-04.log)

**Comment by lxl66566** [comment]
一样的崩溃。多次崩溃之间几乎没有联系，重启无效。
版本：Windows 11 专业版 22H2 22621.521
日志：
[2022-10-07.log](https://github.com/Planshit/Tai/files/9731206/2022-10-07.log)

**Comment by noberumotto** [comment]
@lxl66566 @onelizi 版本太旧了，升级到最新版试试

**Comment by noberumotto** [comment]
谢谢反馈，临时解决方案是在设置>数据中清空当日的数据

**Comment by noberumotto** [comment]
请更新版本试试问题是否已解决

**Comment by onelizi** [comment]
> 置>数据中清空当日的数据

@noberumotto 隔了一天自己好了🤣
Anyway 感谢修复
