### ISSUE TITLE
2个小问题or1个？

### ISSUE THREAD

**Issue by NoclubOIRzXx** [Planshit/Tai#65]
1：管理员模式启动的情况下，无法自启动。通过任务计划启动则打不开或者崩溃。
[2022-09-26.log](https://github.com/Planshit/Tai/files/9714694/2022-09-26.log)

2：统计视图不能正确统计？ 
![image](https://user-images.githubusercontent.com/40497676/194034014-ebbb2297-d0c2-4681-8176-9aad6b4f1297.png)
这里加起来差不多有55分钟，但是比例没显示正确，是大佬设计如此还是错误显示。

**Comment by NoclubOIRzXx** [comment]
系统：Win11 21H2

**Comment by noberumotto** [comment]
管理员模式自启问题确实存在，应该在下一次更新时能解决这个问题；比例没问题，不是按所有分类时长总和显示的

**Comment by noberumotto** [comment]
已解决管理员自启问题，请更新版本。
