### ISSUE TITLE
给应用分类可以增加一些更快捷的方式吗？

### ISSUE THREAD

**Issue by rebron1900** [Planshit/Tai#67]
目前想要添加一个分类要

1. 分类Tab
2. 点击已有分类
3. 点击添加应用
4. 在茫茫多的应用里去找自己的应用。

希望简化这个流程，直接在界面的任意有图标的地方都能通过右键弹出菜单设置分类（我发现目前似乎所有有图标的地方都没有右键功能？）

**Comment by noberumotto** [comment]
收到

**Comment by noberumotto** [comment]
1.2.0.0版本已经加入，记得更新
