### ISSUE TITLE
时长统计异常

### ISSUE THREAD

**Issue by qingzhenduyu** [Planshit/Tai#69]
![image](https://user-images.githubusercontent.com/56719355/197116707-1bdcd017-e768-4fc9-8358-a66e95cbd3a7.png)

如图，今天还没到13点呢，为啥Tai app会记录13点之后的使用时间？
已知，我的电脑自动休眠之后打开Tai就编程这样子了

**Comment by noberumotto** [comment]
可以上传一下21号也就是截图当天的log文件吗？在\log目录下

**Comment by qingzhenduyu** [comment]
> 可以上传一下21号也就是截图当天的log文件吗？在\log目录下
在issue里反馈这个bug之后出现了崩溃的问题，我之后就把log发到您的邮箱了，邮件标题是“崩溃bug待修复”，发送时间是10-21 15:01 请您查收。

**Comment by noberumotto** [comment]
已修复更新，请更新版本到 [1.3.0.0](https://github.com/Planshit/Tai/releases/tag/1.3.0.0) 观察几天看是否已经解决此问题
