### ISSUE TITLE
分类颜色不同步

### ISSUE THREAD

**Issue by XiaoDuComrade** [Planshit/Tai#71]
在统计界面中，按天的分类颜色显示和分类中设置的一致，但按周 按月 按年都和分类中设置的颜色不同步。
![image](https://user-images.githubusercontent.com/69492720/198182201-9923dbea-455d-4c38-be5d-d1163afa37cf.png)
![image](https://user-images.githubusercontent.com/69492720/198182213-d11b42e5-5912-43b9-9c73-b5875e3b2d69.png)
![image](https://user-images.githubusercontent.com/69492720/198182233-94aa54b8-6d9a-4259-8476-cf6117e62076.png)

**Comment by noberumotto** [comment]
已修复此问题 https://github.com/Planshit/Tai/releases/tag/1.3.0.1
