### ISSUE TITLE
软件闪退bug

### ISSUE THREAD

**Issue by lxl66566** [Planshit/Tai#72]
笔记本断开电源后，程序闪退。日志中没有记录。测试时关闭了所有窗口与后台程序（除了七彩虹控制中心Control Center3.0），仍然闪退。

Tai版本：1.3.0.0
笔记本型号：七彩虹将星x15 xs
windows型号：Windows 11 专业版  22H2 22621.674

**Comment by lxl66566** [comment]
今天向 `data.db` 表 CategoryModels 的 Color 字段添加了颜色值，就不会闪退了。原本此处的值为空。应该是 1.0.x 的 data 格式问题？

**Comment by lxl66566** [comment]
> 今天向 `data.db` 表 CategoryModels 的 Color 字段添加了颜色值，就不会闪退了。原本此处的值为空。应该是 1.0.x 的 data 格式问题？

呃，抱歉，今天还是闪退了，不是这个问题（

**Comment by noberumotto** [comment]
断开电源是指把笔记本电源线断开的意思吗？如果是的话我测试无法复现😥

**Comment by lxl66566** [comment]
感谢回复，麻烦您了。不能复现确实没什么好办法。

**Comment by noberumotto** [comment]
1. 试试将data文件夹删除后（记得备份）再测试一遍断开电源看看是否还会闪退。
2. 理论上由程序自身出现的问题导致的崩溃是会留下日志并且弹出崩溃提示窗口的，如果没看到日志中存在崩溃异常的记录也没显示弹窗有可能是外部程序将 Tai 的进程杀掉了，这个时候可以安装一个虚拟机，在虚拟机中运行 Tai ，然后重复断开电源的操作，如果不会闪退则证实了是宿主机中的某个软件将 Tai 干掉了。
我会持续关注这个问题，非常谢谢反馈。
