### ISSUE TITLE
闪退崩溃

### ISSUE THREAD

**Issue by NoclubOIRzXx** [Planshit/Tai#73]
操作细节：在统计里面选择其中的某个时间段里的软件，右键忽略此应用就会崩溃
![Tai_K1AtQQzUBw](https://user-images.githubusercontent.com/40497676/201076352-42dfe8f2-a8e1-4778-a4b0-22cb65fbbe46.gif)
[2022-11-10.log](https://github.com/Planshit/Tai/files/9980121/2022-11-10.log)

**Comment by NoclubOIRzXx** [comment]
崩溃日志在结尾

**Comment by noberumotto** [comment]
已修复此问题 https://github.com/Planshit/Tai/releases/tag/1.3.0.1
