### ISSUE TITLE
外接显示屏只能记录主屏幕的使用时间

### ISSUE THREAD

**Issue by 595624187** [Planshit/Tai#75]
下图是今天到9点到10点的记录
我是一直在使用电脑，只是有时候在副屏上，使用时间应该是2小时，但是只记录了一部分，导致只记录了主屏幕使用的30分钟。
![图片](https://user-images.githubusercontent.com/38000873/202954239-7e07f5a4-983d-490b-bfde-6ddea1884949.png)
我的副屏是竖着的，所以截图下来是下面的。
![图片](https://user-images.githubusercontent.com/38000873/202954505-da2c1e89-086b-4bdc-81aa-0d17d79c761f.png)

**Comment by 595624187** [comment]
不知道可不可以解决，现在不管是办公还是其他的，都喜欢使用双屏

**Comment by noberumotto** [comment]
好像是没问题的，单看9点的时长总和已经有53分钟了。是不是这种按分类的展示方式会让大家看不明白？

**Comment by 595624187** [comment]
![图片](https://user-images.githubusercontent.com/38000873/204079755-4a051a1f-509b-455b-9d9f-bc4a3f74c324.png)
哦，我仔细看了看，好像是够的。我是手机上那个系统带的时间统计的图看多了，上面这个图是堆一起的，而不是叠加的。
