### ISSUE TITLE
[Feature] Show detailed web browsing time

### ISSUE THREAD

**Issue by Weilet** [Planshit/Tai#76]
Showing detailed web browsing time can help user better manager their time, Is there any way to implement it?

**Comment by noberumotto** [comment]
也许未来会以插件的形式提供

**Comment by noberumotto** [comment]
[Tai 1.5.0.0 已发布 →](https://github.com/Planshit/Tai/releases/tag/1.5.0.0) 请更新版本，等待后续反馈。
