### ISSUE TITLE
从1.0.1升级1.3.x之后历史数据丢失

### ISSUE THREAD

**Issue by tediorelee** [Planshit/Tai#77]
今年截止到我更新tai之前数据都有记录，换了电脑也是正常，但是今天更新了最新版发现历史数据全部没有了，有办法找回吗

![image](https://user-images.githubusercontent.com/48272067/203461193-f5f5e1d6-462b-4471-aaca-efe6d0540661.png)

**Comment by noberumotto** [comment]
在data目录下会有一个备份文件名字大概是backup格式结尾，建议不要操作，先备份整个data文件夹。稍晚点时间我帮你处理，如果没有敏感数据可以打包发到我邮箱（不需要icon文件）

**Comment by tediorelee** [comment]
> 在data目录下会有一个备份文件名字大概是backup格式结尾，建议不要操作，先备份整个data文件夹。稍晚点时间我帮你处理，如果没有敏感数据可以打包发到我邮箱（不需要icon文件）

已私发邮件
