### ISSUE TITLE
当程序列表多了点（12个），概览滚动条有点卡顿（比较明显）。

### ISSUE THREAD

**Issue by K2M74** [Planshit/Tai#8]
20H2  19042.868

**Comment by noberumotto** [comment]
谢谢反馈，下一个版本将会尝试优化。如果可以请回复一下你的硬件信息

**Comment by K2M74** [comment]
@noberumotto https://detail.zol.com.cn/1332/1331207/param.shtml  笔记本直接贴网址算了.....

**Comment by xujinhui2015** [comment]
我的也是上下滑的时候会卡顿，联想yoga14s。

**Comment by noberumotto** [comment]
因技术瓶颈，我暂时处理不掉这个问题，希望有其他开发者能提供一下帮助谢谢

**Comment by noberumotto** [comment]
> 我的也是上下滑的时候会卡顿，联想yoga14s。

是否方便录制一个卡顿录屏的gif或视频贴上来呢？因为我使用台式机并没有出现卡顿现象，所以想看看卡顿的情况，只需要看到卡顿区域即可

**Comment by xujinhui2015** [comment]
https://user-images.githubusercontent.com/16284992/148203419-836c13f9-0d04-48ab-ac24-d805c7340821.mp4

我在详细里面下拉就很丝滑。在概览那里，就能感觉到指针跟不上我的拖动，视频看还没那么明显。

**Comment by noberumotto** [comment]
非常谢谢！在下一次更新时一定解决掉这个问题

**Comment by noberumotto** [comment]
已经更新，请升级版本试试是否解决问题，[1.0.0.2](https://github.com/Planshit/Tai/releases/tag/1.0.0.2)
