### ISSUE TITLE
年统计下的时间总计有点问题。

### ISSUE THREAD

**Issue by rebron1900** [Planshit/Tai#80]
![image](https://user-images.githubusercontent.com/7929884/205424685-e82f4500-c84a-4365-98f8-5c37996ea378.png)

**Comment by noberumotto** [comment]
请更新到1.5.0.0版本看看是否已解决此问题

**Comment by rebron1900** [comment]
可以了，
另外发现新版本可以统计网页了，很赞，网费很贵这个chrome插件可以关闭了。😊
