### ISSUE TITLE
深色模式下,选中此软件后,会有白色边框

### ISSUE THREAD

**Issue by SACMaker** [Planshit/Tai#86]
![image](https://user-images.githubusercontent.com/43346914/208299394-5ab1ef4b-f8c6-49d8-9ff5-ded7482ee71c.png)

**Comment by SACMaker** [comment]
我有强迫症🤣

**Comment by yeungchie** [comment]
+1

**Comment by SACMaker** [comment]
bug fix!Nice job!宝贝!
