### ISSUE TITLE
工作电脑和个人电脑的数据该如何合并

### ISSUE THREAD

**Issue by ottocsb** [Planshit/Tai#87]
rt，工作电脑在公司，下班回家使用个人电脑，但是想两个数据可以合并？因时间上并不冲突，把两份data.db合并可以解决吗，我不太清楚数据库的操作抱歉

**Comment by noberumotto** [comment]
目前版本没有提供合并的支持，但是可以尝试手动操作，需要注意的是如果两台电脑存在相同的软件可能会导致数据不正确。

手动合并的方法：

1. 使用数据库管理工具将其中一个data.db数据导出，然后将导出的数据导入到另一个数据库中；
2. 同时将两个 `AppIcons` 文件夹合并。

**Comment by ottocsb** [comment]
thanks
