### ISSUE TITLE
能否隐藏某些经常占用焦点的软件？

### ISSUE THREAD

**Issue by Mr54233** [Planshit/Tai#9]
例如：https://github.com/mydockfinder/mydockfinder-for-Win10-Win11

![image](https://user-images.githubusercontent.com/46802509/146645951-27218beb-3bd4-4135-86f4-828b11e2fc2b.png)

**Comment by noberumotto** [comment]
下一个版本将会带有进程忽略功能

**Comment by noberumotto** [comment]
1.0.0.1版本已加入自定义隐藏（忽略）进程功能
