### ISSUE TITLE
增加浏览器页面统计

### ISSUE THREAD

**Issue by wzkagms** [Planshit/Tai#90]
例如我在电脑上将网站YouTube添加为应用，但现在我在这个应用上所耗时间会被算进浏览器，希望可以单独识别

**Comment by noberumotto** [comment]
已经在开发中了

**Comment by noberumotto** [comment]
[Tai 1.5.0.0 已发布 →](https://github.com/Planshit/Tai/releases/tag/1.5.0.0) 请更新版本，等待后续反馈。
